spring:
  application:
    name: apaas
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.4.5.118:30012/city_ioc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  mvc:
    dispatch-options-request: true

server:
  port: 9999
